##Datasource Configuration
#spring.datasource.hikari.maximum-pool-size=4
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=ace007
#spring.datasource.platform=postgres


spring:
  r2dbc:
    url: r2dbc:pool:mysql://10.0.1.11:3306/CEMS_DEV # schema ??? webflux? ???
    username: cems_dev
    password: thingspire1945

# ?? ?? - R2DBC?? Database? ??? ??? ?? ??? ???? ????? ???? ?
logging:
  level:
    org.springframework.r2dbc.core: debug